# Generated by Django 4.2.17 on 2025-01-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzlebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('vicon', models.CharField(max_length=200)),
                ('estatus', models.CharField(max_length=200)),
            ],
        ),
    ]
